[project]
name = "lle"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]

[tool.poetry]
name = "lle"
version = "0.1.0"
description = "Laser Learning Environment (LLE) for Multi-Agent Reinforcement Learning"
authors = ["Yannick Molinghen <yannick.molinghen@ulb.be>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10"
numpy = "^1.25.0"
rlenv = { git = "https://github.com/yamoling/rlenv.git" }

[tool.poetry.group.dev.dependencies]
maturin = "^1.1.0"
pytest = "^7.4.0"
mypy = "^1.5.1"

[build-system]
requires = ["maturin>=1.1,<2.0"]
build-backend = "maturin"

[tool.maturin]
python-source = "python"             # Target directory
features = ["pyo3/extension-module"]


[tool.pytest.ini_options]
pythonpath = ["python"]
testpaths = ["python/tests"]

[tool.pylint.format]
max-line-length = 140


[tool.ruff]
line-length = 140

[tool.pyright]
typeCheckingMode = "basic"       # "strict", "off"
include = ["src"]
reportPrivateImportUsage = false
